// 3rd_party_lib:diffutils4cj/build/release/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestDiffUtilsV002{
    /***
        public static func patch<T>(original: ArrayList<T>, patch: Patch<T>): ArrayList<T>
        测试场景:返回patch.applyTo(original)的结果.特殊场景无需验证,patch相关方法已验证
    ***/
    @TestCase
    func testDiffUtilsPatch01(): Unit {
        var original01=Chunk(2,ArrayList<Int64>([1,2,3]))
        var original02=Chunk(1,ArrayList<Int64>([7, 3, 4, 5, 7, 8]))
        var original03=Chunk(1,ArrayList<Int64>([10, 11, 12, 13, 14]))
        var revised01=Chunk(3,Array<Int64>([3,4,5,7,8,6]))
        var revised02=Chunk(1,Array<Int64>([3,4,5,7,8,6]))
        var revised03=Chunk(1,Array<Int64>([3,4,5,7,8,6]))
        let changeDelta=ChangeDelta(original01,revised01)
        let deleteDelta=DeleteDelta(original02,revised02)
        let insertDelta=InsertDelta(original03,revised03)
        var patch=Patch<Int64>()
        patch.addDelta(changeDelta)
        patch.addDelta(insertDelta)
        patch.addDelta(deleteDelta)
        var target=ArrayList<Int64>([2, 7, 1, 2, 3, 8, 9, 7, 1])
        let exp_result=patch.applyTo(target)
        let result=DiffUtils.patch(target,patch)
        @Assert(result,exp_result)
    }
}