// 3rd_party_lib:diffutils4cj/build/diffUtils4cj
// dependence: ../common_Values.cj
from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestDiffUtilsB001{
    /***
        public static func diff<T>(original: ArrayList<T>, revised: ArrayList<T>,algorithm: DiffAlgorithm<T>): Patch<T> where T <: Equal<T> & ToString
        测试场景:original!=revised,original有revised中没有的元素,original没有revised中有的元素
    ***/
    public var original=ArrayList<String>(["value01","value02","value03","old","value04","value05","value06","value07"])
    public var revised=ArrayList<String>(["value02","value03","value04","value05","value06","new","value07","value08"])
    @TestCase
    func testDiffUtilsDiff231(): Unit {
        var algorithm01=MyersDiff<String>()
        var pathch01=DiffUtils.diff(original,revised,algorithm01)
        var deltas01=pathch01.getDeltas()
        @Assert(deltas01.size,4)

        @Assert(deltas01[0] is DeleteDelta<String>,true)
        @Assert(deltas01[0].getOriginal().getLines(),ArrayList<String>(["value01"]))
        @Assert(deltas01[0].getRevised().getLines(),ArrayList<String>([]))

        @Assert(deltas01[1] is DeleteDelta<String>,true)
        @Assert(deltas01[1].getOriginal().getLines(),ArrayList<String>(["old"]))
        @Assert(deltas01[1].getRevised().getLines(),ArrayList<String>([]))

        @Assert(deltas01[2] is InsertDelta<String>,true)
        @Assert(deltas01[2].getOriginal().getLines(),ArrayList<String>([]))
        @Assert(deltas01[2].getRevised().getLines(),ArrayList<String>(["new"]))

        @Assert(deltas01[3] is InsertDelta<String>,true)
        @Assert(deltas01[3].getOriginal().getLines(),ArrayList<String>([]))
        @Assert(deltas01[3].getRevised().getLines(),ArrayList<String>(["value08"]))
    }
    @TestCase
    func testDiffUtilsDiff232(): Unit {
        var algorithm02=MyersDiff<String>(SubEqualizer01<String>())
        var pathch02=DiffUtils.diff(original,revised,algorithm02)
        var deltas02=pathch02.getDeltas()
        @Assert(deltas02.size,4)

        @Assert(deltas02[0] is DeleteDelta<String>,true)
        @Assert(deltas02[0].getOriginal().getLines(),ArrayList<String>(["value01"]))
        @Assert(deltas02[0].getRevised().getLines(),ArrayList<String>([]))

        @Assert(deltas02[1] is DeleteDelta<String>,true)
        @Assert(deltas02[1].getOriginal().getLines(),ArrayList<String>(["old"]))
        @Assert(deltas02[1].getRevised().getLines(),ArrayList<String>([]))

        @Assert(deltas02[2] is InsertDelta<String>,true)
        @Assert(deltas02[2].getOriginal().getLines(),ArrayList<String>([]))
        @Assert(deltas02[2].getRevised().getLines(),ArrayList<String>(["new"]))

        @Assert(deltas02[3] is InsertDelta<String>,true)
        @Assert(deltas02[3].getOriginal().getLines(),ArrayList<String>([]))
        @Assert(deltas02[3].getRevised().getLines(),ArrayList<String>(["value08"]))
    }
}