// 3rd_party_lib:diffutils4cj/build/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestChunkB001{
    /***
        public func verify(target: ArrayList<T>): Unit
        public init(position: Int64, lines: ArrayList<T>)
        public init(position: Int64, lines: Array<T>)
        测试场景:last()=target.size,lines不为空,循环target.get(position + i)==lines.get(i)均成立
    ***/
    @TestCase
    func testChunkVerify0203(): Unit {
        var target=ArrayList<Char>(Array<Char>(250,item:'c'))
        var lines_arrlist=ArrayList<Char>(Array<Char>(100,item:'c'))
        var lines_arr=Array<Char>(100,item:'c')
        var chunk01=Chunk(123,lines_arrlist)//last()=224,size=100
        var chunk02=Chunk(123,lines_arr)//last()=224,size=100
        var flag=0
        try{
            chunk01.verify(target)
        }catch(e:PatchFailedException){
           flag=1
        }
        @Assert(flag,0)
        try{
            chunk01.verify(target)
        }catch(e:PatchFailedException){
           flag=1
        }
        @Assert(flag,0)
    }
}