// 3rd_party_lib:diffutils4cj/build/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestDeltaV002{
    /***
        public init(original: Chunk<T>, revised: Chunk<T> )
        public func equals(obj: Delta<T>): Bool
        测试场景:抽象类，与该子类对象本身对比
    ***/
    @TestCase
    func testDeltaEquals01(): Unit {
        var original=Chunk(123,ArrayList<Int64>([1,2,3,4,5,6]))
        var revised=Chunk(123,Array<Int64>([1,2,3,4,5,6]))
        let changeDelta=ChangeDelta(original,revised)
        let deleteDelta=DeleteDelta(original,revised)
        let insertDelta=InsertDelta(original,revised)
        @Assert(changeDelta.equals(changeDelta),true)
        @Assert(deleteDelta.equals(deleteDelta),true)
        @Assert(insertDelta.equals(insertDelta),true)
    }
}