// 3rd_party_lib:diffutils4cj/build/release/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestPatchV002{
    /***
        public init()
        public func restore(target: ArrayList<T>): ArrayList<T>
        测试场景:Patch中没有Delta,target为空
    ***/
    @TestCase
    func testPatchRestore01(): Unit {
        var patch=Patch<Int64>()
        var target=ArrayList<Int64>()
        let result=patch.restore(target)
        var exp_result=ArrayList<Int64>()
        @Assert(result,exp_result)
    }
}