// 3rd_party_lib:diffutils4cj/build/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestPatchV002{
    /***
        public init()
        public func restore(target: ArrayList<T>): ArrayList<T>
        测试场景:Patch中仅有ChangeDelta,target非空
    ***/
    @TestCase
    func testPatchRestore05(): Unit {
        var original=Chunk(2,ArrayList<Int64>([1,2,3]))
        var revised=Chunk(3,Array<Int64>([3,4,5,7,8,6]))
        let changeDelta=ChangeDelta(original,revised)
        var patch=Patch<Int64>()
        patch.addDelta(changeDelta)
        var target=ArrayList<Int64>([2, 7, 1, 7, 1, 2, 3, 8, 9])
        let result=patch.restore(target)
        var exp_result=ArrayList<Int64>([2, 7, 1, 1, 2, 3])
        @Assert(result,exp_result)
    }
}