// 3rd_party_lib:diffutils4cj/build/release/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestDeleteDeltaV002{
    /***
        public init(original: Chunk<T>, revised: Chunk<T> )
        public func applyTo(target: ArrayList<T>): Unit
        测试场景:verify结果正常(original.verify(target)正常)
                original.getPosition()<0 && original.size()>0---走循环索引为-1
    ***/
    @TestCase
    func testDeleteDeltaApplyTo03(): Unit {
        var original=Chunk(-1,ArrayList<Int64>())
        var revised=Chunk(1,Array<Int64>([1]))
        let deleteDelta=DeleteDelta(original,revised)
        var target=ArrayList<Int64>()
        var flag=1
        try{
            deleteDelta.applyTo(target)
        }catch(e:IndexOutOfBoundsException){
            flag=0
        }
        @Assert(flag,1)
    }
}