// 3rd_party_lib:diffutils4cj/build/release/diffUtils4cj
// 3rd_party_lib_ohos:diffutils4cj/build/aarch64-linux-ohos/diffUtils4cj
// dependence: ../common_Values.cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestMyersDiffB001{
    /***
        public func diff(original: Array<T>, revised: Array<T>): Patch<T>
        public init(equalizer: Equalizer<T>)
        public init()
        测试场景:original==revised,均为空
    ***/
    public var arr=Array<String>()
    @TestCase
    func testMyersDiffMyersDiff0111(): Unit {
        var myersDiff01=MyersDiff<String>()
        var pathch01=myersDiff01.diff(arr,arr)
        @Assert(pathch01.getDeltas().size,0)
    }
    @TestCase
    func testMyersDiffMyersDiff0112(): Unit {
        var myersDiff02=MyersDiff<String>(SubEqualizer01<String>())
        var pathch02=myersDiff02.diff(arr,arr)
        @Assert(pathch02.getDeltas().size,0)
    }
}