// 3rd_party_lib:diffutils4cj/build/diffUtils4cj
// dependence: ../common_Values.cj
from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestMyersDiffB001{
    /***
        public func buildPath(orig:  ArrayList<T>, rev:  ArrayList<T>): PathNode
        public init(equalizer: Equalizer<T>)
        public init()
        测试场景:仅orig为空
    ***/
    public var orig=ArrayList<String>()
    public var rev=ArrayList<String>(["as","bg","rf","cd"])
    @TestCase
    func testMyersDiffBuildPath011(): Unit {
        var myersDiff01=MyersDiff<String>()
        var pathNode01=myersDiff01.buildPath(orig,rev)
        @Assert(pathNode01.toString(),"[(0,4)(0,0)]")
    }
    @TestCase
    func testMyersDiffBuildPath012(): Unit {
        var myersDiff02=MyersDiff<String>(SubEqualizer01<String>())
        var pathNode02=myersDiff02.buildPath(orig,rev)
        @Assert(pathNode02.toString(),"[(0,4)(0,0)]")
    }
}