// 3rd_party_lib:diffutils4cj/build/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from std import collection.*
from diffUtils4cj import diffUtils4cj.*

@Test
public class TestDiffRowGenerator{
    /***
        public static func wrapInTag(sequence: ArrayList<String>, startPosition: Int64, endPosition: Int64,tag: String, cssClass: Option<String>): ArrayList<String>
        测试场景:列表不为空,cssClass为Option<String>.None,endPosition>sequence.size+2
    ***/
    @TestCase
    func testDiffRowGeneratorWrapInTag0204(): Unit {
        let sequence=ArrayList<String>(["1","2","3","4","5"])
        let startPosition=sequence.size
        let endPosition=sequence.size+3
        let tag="tag"
        let cssClass=Option<String>.None
        var re_wrapInTag_flag=0
        try{
            DiffRowGenerator.wrapInTag(sequence,startPosition,endPosition,tag,cssClass)
        }catch(e:IndexOutOfBoundsException){
            re_wrapInTag_flag=1
        }
        @Assert(re_wrapInTag_flag,1)
    }
}