// 3rd_party_lib:diffutils4cj/build/diffUtils4cj

from std import unittest.*
from std import unittest.testmacro.*
from diffUtils4cj import diffUtils4cj.*
from std import collection.*

@Test
public class TestDiffRowGenerator{
    /***
        public func generateDiffRows(original: ArrayList<String>, revised: ArrayList<String>, patch: Patch<String>): ArrayList<DiffRow>
        测试场景:patch仅有DeleteDelta,original,revised非空,且chunk_ori_lines.size==chunk_rev_lines.size
    ***/
    @TestCase
    func testDiffRowGeneratorGenerateDiffRows0110(): Unit {
        let original=ArrayList<String>(["12","34","56","78","12","34","56","78","12","34","56","78"])
        let revised=ArrayList<String>(["910","911","912"])
        var patch=Patch<String>()
        let chunk_ori_lines=ArrayList<String>(["1\t4","2","3<6","4","5>34","6"])
        let chunk_ori=Chunk(3,chunk_ori_lines)
        let chunk_rev_lines=ArrayList<String>(["7>11","8\t\t7","9<34","10","9<34","10"])
        let chunk_rev=Chunk(3,chunk_rev_lines)
        let deleteDelta=DeleteDelta(chunk_ori,chunk_rev)
        patch.addDelta(deleteDelta)
        var builder=Builder()
        let diffRowGenerator=builder.build()
        let re_generateDiffRows=diffRowGenerator.generateDiffRows(original,revised,patch).toString()
        let exp_generateDiffRows="[[EQUAL,12,12], [EQUAL,34,34], [EQUAL,56,56], [DELETE,1    4,], [DELETE,2,], [DELETE,3&lt;6,], [DELETE,4,], [DELETE,5&gt;34,], [DELETE,6,], [EQUAL,34,34], [EQUAL,56,56], [EQUAL,78,78]]"
        @Assert(re_generateDiffRows,exp_generateDiffRows)
    }
}

